export const mockData = [
    {
        id: 1,
        name: 'John Doe',
        email: 'johndoe@example.com',
        phone: '123-456-7890',
        city: 'Delhi',
        budget: '10,000',
    },
    {
        id: 2,
        name: 'Jane Smith',
        email: 'janesmith@example.com',
        phone: '987-654-3210',
        city: 'Delhi',
        budget: '10,000',
    },
    {
        id: 3,
        name: 'Michael Johnson',
        email: 'michaeljohnson@example.com',
        phone: '555-123-4567',
        city: 'Delhi',
        budget: '10,000',
    },
    {
        id: 4,
        name: 'Emily Wilson',
        email: 'emilywilson@example.com',
        phone: '999-888-7777',
        city: 'Delhi',
        budget: '10,000',
    },
    {
        id: 5,
        name: 'Daniel Lee',
        email: 'daniellee@example.com',
        phone: '444-555-6666',
        city: 'Delhi',
        budget: '10,000',
    },
    {
        id: 6,
        name: 'Olivia Martinez',
        email: 'oliviamartinez@example.com',
        phone: '777-999-1111',
        city: 'Delhi',
        budget: '10,000',
    },
    {
        id: 7,
        name: 'William Thompson',
        email: 'williamthompson@example.com',
        phone: '222-333-4444',
        city: 'Delhi',
        budget: '10,000',
    },
]
