import ranbir from '../assets/clients/ranbir.png'

export const team = [
    {
        id: 1,
        img: ranbir,
        name: 'Ishat Jain',
        positon: 'Founder',
        country: 'INDIA',
        countryLogo: '',
    },
    {
        id: 2,
        img: ranbir,
        name: 'Ishat Jain',
        positon: 'Founder',
        country: 'INDIA',
        countryLogo: '',
    },
    {
        id: 3,
        img: ranbir,
        name: 'Ishat Jain',
        positon: 'Founder',
        country: 'INDIA',
        countryLogo: '',
    },
    {
        id: 4,
        img: ranbir,
        name: 'Ishat Jain',
        positon: 'Founder',
        country: 'INDIA',
        countryLogo: '',
    },
    {
        id: 5,
        img: ranbir,
        name: 'Ishat Jain',
        positon: 'Founder',
        country: 'INDIA',
        countryLogo: '',
    },
    {
        id: 6,
        img: ranbir,
        name: 'Ishat Jain',
        positon: 'Founder',
        country: 'INDIA',
        countryLogo: '',
    },
    {
        id: 7,
        img: ranbir,
        name: 'Ishat Jain',
        positon: 'Founder',
        country: 'INDIA',
        countryLogo: '',
    },
]
